# fly.toml app configuration file generated for js-ts-intro on 2025-02-07T17:13:25+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'js-ts-intro'
primary_region = 'arn'

[build]
  image = 'ghcr.io/nilshartmann/ecolify-backend-native:5be99f2'

[http_service]
  internal_port = 20080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
